### ISSUE TITLE
persist=False has no effect

### ISSUE THREAD

**Issue by sa9** [LPM-HMS/COSMOS-2.0#17]
Setting ```persist=False``` argument in ```abstract_output_taskfile``` method (part of TaskFile.py) doesn't seem to have an effect. The output fils in each stage or task don't get deleted. 

How can we delete intermediate files?

**Comment by egafni** [comment]
Ah, I never implemented that in cosmos2.

One wasy way to do this is send files you don't want to keep to
output_dir/tmp and then delete the directory upon workflow success

**Comment by sa9** [comment]
Sounds good.  Thanks Erik.

**Comment by egafni** [comment]
Sure if you need it done more on the fly let me know

**Comment by yassineS** [comment]
Actually this is an important feature, since it helps saving storage on the flight, especially while running big datasets such as genomes on limited storage, it can generate up to 5 times tmp files.


On Jul 26, 2015, at 6:51 PM, Erik <notifications@github.com> wrote:

Sure if you need it done more on the fly let me know

**Comment by yassineS** [comment]
Actually this is an important feature, since it helps saving storage on the flight, especially while running big datasets such as genomes on limited storage, it can generate up to 5 times tmp files.


On Jul 26, 2015, at 6:51 PM, Erik <notifications@github.com <mailto:notifications@github.com>> wrote:

Sure if you need it done more on the fly let me know

**Comment by egafni** [comment]
Yassine, yes, but if you use S3 it doesn't matter :)

I may implement at some point but its not a high priority unless someone
needs it.  I might also simplify the TaskFile Model to make the api
simpler/easier for users so am resistant to adding dependent features

**Comment by yassineS** [comment]
True, but we have a case where I experimented with the r3 instances and I ran out of space around the middle of the pipeline. Anyways, as you mentioned you can hack it by redirecting the files to the tmp dir but it’ll be nice to have it around.

Thanks

On Jul 27, 2015, at 4:34 PM, Erik <notifications@github.com> wrote:

Yassine, yes, but if you use S3 it doesn't matter :)

I may implement at some point but its not a high priority unless someone
needs it. I might also simplify the TaskFile Model to make the api
simpler/easier for users so am resistant to adding dependent features

**Comment by egafni** [comment]
curious, what did you need hi-mem for?

The ideal scenario is to use S3 rather than a shared-fs (it's basically
free to store the intermediary files until the workflow is done - bonus you
get to have them there to debug).  Another bonus is you don't have to pay
the high instance prices of the high-storage nodes

**Comment by yassineS** [comment]
well the main goal was the brut speed, r3 have SSDs and it is much faster than using S3 or any other solution. We mounted the hard drives in RAID0 for each instance before creating the shared FS. The speed gain was incredible. This is very useful once the pipeline is extensively tested and runs smoothly.


On Jul 27, 2015, at 6:27 PM, Erik <notifications@github.com> wrote:

curious, what did you need hi-mem for?

The ideal scenario is to use S3 rather than a shared-fs (it's basically
free to store the intermediary files until the workflow is done - bonus you
get to have them there to debug). Another bonus is you don't have to pay
the high instance prices of the high-storage nodes

**Comment by egafni** [comment]
What was the speed gain?  Why not use C3 instance-types?

I tested GKv2 on C3s because of the SSD - even though I'm uploading to S3
files were still being written to the local HD first (auto streaming output
directly to S3 was a bit finicky, but that would certainly be ideal).

I'm generally not so concerned with raw speed since things are
embarrassingly parallel by sample.  If it takes 24 hours to analyze 100
genomes, getting that down to even 5 hours is of little value in real-world
applications, especially if it costs more money.

The simplicity of the S3 solution is also paramount. The code is very
simple, and you don't have to worry about network IO bottlenecks which will
occur with gluster for large workflows.  By directly using S3, you should
be able to analyze 1000+ genomes with one workflow and cluster.

**Comment by egafni** [comment]
Yassine,

Have you tried enabling enhanced network performance for gluster?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

**Comment by yassineS** [comment]
Will give it a shot.


On Jul 27, 2015, at 10:57 PM, Erik <notifications@github.com> wrote:

Yassine,

Have you tried enabling enhanced network performance for gluster?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html
